version: "3.9"

services:
  notification-service:
    build: .
    container_name: notification-service
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/notificationsdb

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:1.0.0-alpha
    container_name: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=
      - ME_CONFIG_MONGODB_ADMINPASSWORD=
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=secret

volumes:
  mongo-data:
